# Generated by Django 4.2.7 on 2023-11-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('Ожидает ответа', 'Ожидает ответа'), ('Принят', 'Принят'), ('Отклонен', 'Отклонен')], default='Ожидает ответа', max_length=20),
        ),
    ]
